namespace SterlingLams.Web.Models.Domain;

/// <summary>
/// A timeline note on an order (WooCommerce-style). System notes are auto-generated at key events
/// (payment, stock reduced, status change, auto-cancel, refund); staff notes are added by hand.
/// A "customer note" is also emailed to the buyer; a "private note" is internal only.
/// </summary>
public class OrderNote
{
    public int Id { get; set; }

    public int OrderId { get; set; }
    public Order Order { get; set; } = null!;

    public string Content { get; set; } = string.Empty;

    /// <summary>Auto-generated by the system (rendered differently from staff notes).</summary>
    public bool IsSystem { get; set; }

    /// <summary>A note to the customer (emailed). False = private/internal note.</summary>
    public bool IsCustomerNote { get; set; }

    /// <summary>Staff member who wrote it (null for system notes).</summary>
    public string? AuthorName { get; set; }

    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
}
